### ISSUE TITLE
Clean up the main CI steps

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxscript#1635]
LGTM thanks! There is a step in the ci job

```
      - name: Upload IR profiling results
        if: matrix.name == 'py311' || matrix.name == 'py311-onnx-weekly'
        uses: actions/upload-artifact@v3
        with:
          name: IR profiling results
          path: tests/ir/serde_test_profiles
```

That can be removed too.

_Originally posted by @justinchuby in https://github.com/microsoft/onnxscript/pull/1609#pullrequestreview-2123778224_
